// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';
import type { QueryOperationTypes as PgTargetQueryOps } from '@prisma/orm-postgres/target/operation-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'fdef42c759ebbfe2b46abb596a39d7da34c30bc54fa220aa92daca46c7fcacb2'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgTargetQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Categories: {
      readonly id: CodecTypes['pg/int8@1']['output'];
      readonly slug: CodecTypes['pg/text@1']['output'];
    };
    readonly CategoryTranslations: {
      readonly categoryId: CodecTypes['pg/int8@1']['output'] | null;
      readonly id: CodecTypes['pg/int8@1']['output'];
      readonly languageCode: Varchar<10>;
      readonly name: CodecTypes['pg/text@1']['output'];
    };
    readonly Ingredients: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly id: CodecTypes['pg/int8@1']['output'];
    };
    readonly IngredientTranslations: {
      readonly id: CodecTypes['pg/int8@1']['output'];
      readonly ingredientId: CodecTypes['pg/int8@1']['output'] | null;
      readonly languageCode: Varchar<10>;
      readonly name: CodecTypes['pg/text@1']['output'];
    };
    readonly Recipes: {
      readonly authorId: CodecTypes['pg/uuid@1']['output'] | null;
      readonly categoryId: CodecTypes['pg/int8@1']['output'] | null;
      readonly cookingTime: CodecTypes['pg/int4@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly id: CodecTypes['pg/int8@1']['output'];
      readonly imageUrl: CodecTypes['pg/text@1']['output'] | null;
      readonly servings: CodecTypes['pg/int4@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
    };
    readonly RecipeSteps: {
      readonly id: CodecTypes['pg/int8@1']['output'];
      readonly imageUrl: CodecTypes['pg/text@1']['output'] | null;
      readonly recipeId: CodecTypes['pg/int8@1']['output'] | null;
      readonly stepNumber: CodecTypes['pg/int4@1']['output'];
    };
    readonly RecipeStepTranslations: {
      readonly id: CodecTypes['pg/int8@1']['output'];
      readonly instruction: CodecTypes['pg/text@1']['output'];
      readonly languageCode: Varchar<10>;
      readonly stepId: CodecTypes['pg/int8@1']['output'] | null;
    };
    readonly RecipeTranslations: {
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/int8@1']['output'];
      readonly languageCode: Varchar<10>;
      readonly recipeId: CodecTypes['pg/int8@1']['output'] | null;
      readonly title: CodecTypes['pg/text@1']['output'];
    };
    readonly Units: { readonly code: Varchar<50>; readonly id: CodecTypes['pg/int8@1']['output'] };
    readonly UnitTranslations: {
      readonly id: CodecTypes['pg/int8@1']['output'];
      readonly label: Varchar<50>;
      readonly languageCode: Varchar<10>;
      readonly unitId: CodecTypes['pg/int8@1']['output'] | null;
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Categories: {
      readonly id: CodecTypes['pg/int8@1']['input'];
      readonly slug: CodecTypes['pg/text@1']['input'];
    };
    readonly CategoryTranslations: {
      readonly categoryId: CodecTypes['pg/int8@1']['input'] | null;
      readonly id: CodecTypes['pg/int8@1']['input'];
      readonly languageCode: CodecTypes['sql/varchar@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
    };
    readonly Ingredients: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly id: CodecTypes['pg/int8@1']['input'];
    };
    readonly IngredientTranslations: {
      readonly id: CodecTypes['pg/int8@1']['input'];
      readonly ingredientId: CodecTypes['pg/int8@1']['input'] | null;
      readonly languageCode: CodecTypes['sql/varchar@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
    };
    readonly Recipes: {
      readonly authorId: CodecTypes['pg/uuid@1']['input'] | null;
      readonly categoryId: CodecTypes['pg/int8@1']['input'] | null;
      readonly cookingTime: CodecTypes['pg/int4@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly id: CodecTypes['pg/int8@1']['input'];
      readonly imageUrl: CodecTypes['pg/text@1']['input'] | null;
      readonly servings: CodecTypes['pg/int4@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
    };
    readonly RecipeSteps: {
      readonly id: CodecTypes['pg/int8@1']['input'];
      readonly imageUrl: CodecTypes['pg/text@1']['input'] | null;
      readonly recipeId: CodecTypes['pg/int8@1']['input'] | null;
      readonly stepNumber: CodecTypes['pg/int4@1']['input'];
    };
    readonly RecipeStepTranslations: {
      readonly id: CodecTypes['pg/int8@1']['input'];
      readonly instruction: CodecTypes['pg/text@1']['input'];
      readonly languageCode: CodecTypes['sql/varchar@1']['input'];
      readonly stepId: CodecTypes['pg/int8@1']['input'] | null;
    };
    readonly RecipeTranslations: {
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/int8@1']['input'];
      readonly languageCode: CodecTypes['sql/varchar@1']['input'];
      readonly recipeId: CodecTypes['pg/int8@1']['input'] | null;
      readonly title: CodecTypes['pg/text@1']['input'];
    };
    readonly Units: {
      readonly code: CodecTypes['sql/varchar@1']['input'];
      readonly id: CodecTypes['pg/int8@1']['input'];
    };
    readonly UnitTranslations: {
      readonly id: CodecTypes['pg/int8@1']['input'];
      readonly label: CodecTypes['sql/varchar@1']['input'];
      readonly languageCode: CodecTypes['sql/varchar@1']['input'];
      readonly unitId: CodecTypes['pg/int8@1']['input'] | null;
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly categories: {
      readonly id: CodecTypes['pg/int8@1']['output'];
      readonly slug: CodecTypes['pg/text@1']['output'];
    };
    readonly category_translations: {
      readonly category_id: CodecTypes['pg/int8@1']['output'] | null;
      readonly id: CodecTypes['pg/int8@1']['output'];
      readonly language_code: Varchar<10>;
      readonly name: CodecTypes['pg/text@1']['output'];
    };
    readonly ingredient_translations: {
      readonly id: CodecTypes['pg/int8@1']['output'];
      readonly ingredient_id: CodecTypes['pg/int8@1']['output'] | null;
      readonly language_code: Varchar<10>;
      readonly name: CodecTypes['pg/text@1']['output'];
    };
    readonly ingredients: {
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly id: CodecTypes['pg/int8@1']['output'];
    };
    readonly recipe_step_translations: {
      readonly id: CodecTypes['pg/int8@1']['output'];
      readonly instruction: CodecTypes['pg/text@1']['output'];
      readonly language_code: Varchar<10>;
      readonly step_id: CodecTypes['pg/int8@1']['output'] | null;
    };
    readonly recipe_steps: {
      readonly id: CodecTypes['pg/int8@1']['output'];
      readonly image_url: CodecTypes['pg/text@1']['output'] | null;
      readonly recipe_id: CodecTypes['pg/int8@1']['output'] | null;
      readonly step_number: CodecTypes['pg/int4@1']['output'];
    };
    readonly recipe_translations: {
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/int8@1']['output'];
      readonly language_code: Varchar<10>;
      readonly recipe_id: CodecTypes['pg/int8@1']['output'] | null;
      readonly title: CodecTypes['pg/text@1']['output'];
    };
    readonly recipes: {
      readonly author_id: CodecTypes['pg/uuid@1']['output'] | null;
      readonly category_id: CodecTypes['pg/int8@1']['output'] | null;
      readonly cooking_time: CodecTypes['pg/int4@1']['output'];
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly id: CodecTypes['pg/int8@1']['output'];
      readonly image_url: CodecTypes['pg/text@1']['output'] | null;
      readonly servings: CodecTypes['pg/int4@1']['output'];
      readonly updated_at: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
    };
    readonly unit_translations: {
      readonly id: CodecTypes['pg/int8@1']['output'];
      readonly label: Varchar<50>;
      readonly language_code: Varchar<10>;
      readonly unit_id: CodecTypes['pg/int8@1']['output'] | null;
    };
    readonly units: { readonly code: Varchar<50>; readonly id: CodecTypes['pg/int8@1']['output'] };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly categories: {
      readonly id: CodecTypes['pg/int8@1']['input'];
      readonly slug: CodecTypes['pg/text@1']['input'];
    };
    readonly category_translations: {
      readonly category_id: CodecTypes['pg/int8@1']['input'] | null;
      readonly id: CodecTypes['pg/int8@1']['input'];
      readonly language_code: CodecTypes['sql/varchar@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
    };
    readonly ingredient_translations: {
      readonly id: CodecTypes['pg/int8@1']['input'];
      readonly ingredient_id: CodecTypes['pg/int8@1']['input'] | null;
      readonly language_code: CodecTypes['sql/varchar@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
    };
    readonly ingredients: {
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly id: CodecTypes['pg/int8@1']['input'];
    };
    readonly recipe_step_translations: {
      readonly id: CodecTypes['pg/int8@1']['input'];
      readonly instruction: CodecTypes['pg/text@1']['input'];
      readonly language_code: CodecTypes['sql/varchar@1']['input'];
      readonly step_id: CodecTypes['pg/int8@1']['input'] | null;
    };
    readonly recipe_steps: {
      readonly id: CodecTypes['pg/int8@1']['input'];
      readonly image_url: CodecTypes['pg/text@1']['input'] | null;
      readonly recipe_id: CodecTypes['pg/int8@1']['input'] | null;
      readonly step_number: CodecTypes['pg/int4@1']['input'];
    };
    readonly recipe_translations: {
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/int8@1']['input'];
      readonly language_code: CodecTypes['sql/varchar@1']['input'];
      readonly recipe_id: CodecTypes['pg/int8@1']['input'] | null;
      readonly title: CodecTypes['pg/text@1']['input'];
    };
    readonly recipes: {
      readonly author_id: CodecTypes['pg/uuid@1']['input'] | null;
      readonly category_id: CodecTypes['pg/int8@1']['input'] | null;
      readonly cooking_time: CodecTypes['pg/int4@1']['input'];
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly id: CodecTypes['pg/int8@1']['input'];
      readonly image_url: CodecTypes['pg/text@1']['input'] | null;
      readonly servings: CodecTypes['pg/int4@1']['input'];
      readonly updated_at: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
    };
    readonly unit_translations: {
      readonly id: CodecTypes['pg/int8@1']['input'];
      readonly label: CodecTypes['sql/varchar@1']['input'];
      readonly language_code: CodecTypes['sql/varchar@1']['input'];
      readonly unit_id: CodecTypes['pg/int8@1']['input'] | null;
    };
    readonly units: {
      readonly code: CodecTypes['sql/varchar@1']['input'];
      readonly id: CodecTypes['pg/int8@1']['input'];
    };
  };
};

export namespace Models {
  export type public_Categories = {
    id: CodecTypes['pg/int8@1']['output'];
    slug: CodecTypes['pg/text@1']['output'];
    categoryTranslations: public_CategoryTranslations[];
    recipes: public_Recipes[];
    readonly [RelationKeys]?: 'categoryTranslations' | 'recipes';
  };
  export type public_CategoryTranslations = {
    categoryId: CodecTypes['pg/int8@1']['output'] | null;
    id: CodecTypes['pg/int8@1']['output'];
    languageCode: Varchar<10>;
    name: CodecTypes['pg/text@1']['output'];
    category: public_Categories | null;
    readonly [RelationKeys]?: 'category';
  };
  export type public_IngredientTranslations = {
    id: CodecTypes['pg/int8@1']['output'];
    ingredientId: CodecTypes['pg/int8@1']['output'] | null;
    languageCode: Varchar<10>;
    name: CodecTypes['pg/text@1']['output'];
    ingredient: public_Ingredients | null;
    readonly [RelationKeys]?: 'ingredient';
  };
  export type public_Ingredients = {
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
    id: CodecTypes['pg/int8@1']['output'];
    ingredientTranslations: public_IngredientTranslations[];
    readonly [RelationKeys]?: 'ingredientTranslations';
  };
  export type public_RecipeStepTranslations = {
    id: CodecTypes['pg/int8@1']['output'];
    instruction: CodecTypes['pg/text@1']['output'];
    languageCode: Varchar<10>;
    stepId: CodecTypes['pg/int8@1']['output'] | null;
    step: public_RecipeSteps | null;
    readonly [RelationKeys]?: 'step';
  };
  export type public_RecipeSteps = {
    id: CodecTypes['pg/int8@1']['output'];
    imageUrl: CodecTypes['pg/text@1']['output'] | null;
    recipeId: CodecTypes['pg/int8@1']['output'] | null;
    stepNumber: CodecTypes['pg/int4@1']['output'];
    recipe: public_Recipes | null;
    recipeStepTranslations: public_RecipeStepTranslations[];
    readonly [RelationKeys]?: 'recipe' | 'recipeStepTranslations';
  };
  export type public_RecipeTranslations = {
    description: CodecTypes['pg/text@1']['output'] | null;
    id: CodecTypes['pg/int8@1']['output'];
    languageCode: Varchar<10>;
    recipeId: CodecTypes['pg/int8@1']['output'] | null;
    title: CodecTypes['pg/text@1']['output'];
    recipe: public_Recipes | null;
    readonly [RelationKeys]?: 'recipe';
  };
  export type public_Recipes = {
    authorId: CodecTypes['pg/uuid@1']['output'] | null;
    categoryId: CodecTypes['pg/int8@1']['output'] | null;
    cookingTime: CodecTypes['pg/int4@1']['output'];
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
    id: CodecTypes['pg/int8@1']['output'];
    imageUrl: CodecTypes['pg/text@1']['output'] | null;
    servings: CodecTypes['pg/int4@1']['output'];
    updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
    category: public_Categories | null;
    recipeSteps: public_RecipeSteps[];
    recipeTranslations: public_RecipeTranslations[];
    readonly [RelationKeys]?: 'category' | 'recipeSteps' | 'recipeTranslations';
  };
  export type public_UnitTranslations = {
    id: CodecTypes['pg/int8@1']['output'];
    label: Varchar<50>;
    languageCode: Varchar<10>;
    unitId: CodecTypes['pg/int8@1']['output'] | null;
    unit: public_Units | null;
    readonly [RelationKeys]?: 'unit';
  };
  export type public_Units = {
    code: Varchar<50>;
    id: CodecTypes['pg/int8@1']['output'];
    unitTranslations: public_UnitTranslations[];
    readonly [RelationKeys]?: 'unitTranslations';
  };
}

export declare const models: {
  public: {
    Categories: Models.public_Categories;
    CategoryTranslations: Models.public_CategoryTranslations;
    IngredientTranslations: Models.public_IngredientTranslations;
    Ingredients: Models.public_Ingredients;
    RecipeStepTranslations: Models.public_RecipeStepTranslations;
    RecipeSteps: Models.public_RecipeSteps;
    RecipeTranslations: Models.public_RecipeTranslations;
    Recipes: Models.public_Recipes;
    UnitTranslations: Models.public_UnitTranslations;
    Units: Models.public_Units;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly categories: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int8';
                  readonly codecId: 'pg/int8@1';
                  readonly nullable: false;
                };
                readonly slug: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly category_translations: {
              columns: {
                readonly category_id: {
                  readonly nativeType: 'int8';
                  readonly codecId: 'pg/int8@1';
                  readonly nullable: true;
                };
                readonly id: {
                  readonly nativeType: 'int8';
                  readonly codecId: 'pg/int8@1';
                  readonly nullable: false;
                };
                readonly language_code: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 10 };
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly ingredient_translations: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int8';
                  readonly codecId: 'pg/int8@1';
                  readonly nullable: false;
                };
                readonly ingredient_id: {
                  readonly nativeType: 'int8';
                  readonly codecId: 'pg/int8@1';
                  readonly nullable: true;
                };
                readonly language_code: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 10 };
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly ingredients: {
              columns: {
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
                readonly id: {
                  readonly nativeType: 'int8';
                  readonly codecId: 'pg/int8@1';
                  readonly nullable: false;
                };
              };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly recipe_step_translations: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int8';
                  readonly codecId: 'pg/int8@1';
                  readonly nullable: false;
                };
                readonly instruction: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly language_code: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 10 };
                };
                readonly step_id: {
                  readonly nativeType: 'int8';
                  readonly codecId: 'pg/int8@1';
                  readonly nullable: true;
                };
              };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly recipe_steps: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int8';
                  readonly codecId: 'pg/int8@1';
                  readonly nullable: false;
                };
                readonly image_url: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly recipe_id: {
                  readonly nativeType: 'int8';
                  readonly codecId: 'pg/int8@1';
                  readonly nullable: true;
                };
                readonly step_number: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly recipe_translations: {
              columns: {
                readonly description: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly id: {
                  readonly nativeType: 'int8';
                  readonly codecId: 'pg/int8@1';
                  readonly nullable: false;
                };
                readonly language_code: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 10 };
                };
                readonly recipe_id: {
                  readonly nativeType: 'int8';
                  readonly codecId: 'pg/int8@1';
                  readonly nullable: true;
                };
                readonly title: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly recipes: {
              columns: {
                readonly author_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: true;
                };
                readonly category_id: {
                  readonly nativeType: 'int8';
                  readonly codecId: 'pg/int8@1';
                  readonly nullable: true;
                };
                readonly cooking_time: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
                readonly id: {
                  readonly nativeType: 'int8';
                  readonly codecId: 'pg/int8@1';
                  readonly nullable: false;
                };
                readonly image_url: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly servings: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 1>;
                  };
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
              };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly unit_translations: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int8';
                  readonly codecId: 'pg/int8@1';
                  readonly nullable: false;
                };
                readonly label: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 50 };
                };
                readonly language_code: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 10 };
                };
                readonly unit_id: {
                  readonly nativeType: 'int8';
                  readonly codecId: 'pg/int8@1';
                  readonly nullable: true;
                };
              };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly units: {
              columns: {
                readonly code: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 50 };
                };
                readonly id: {
                  readonly nativeType: 'int8';
                  readonly codecId: 'pg/int8@1';
                  readonly nullable: false;
                };
              };
              uniques: readonly [{ readonly columns: readonly ['code'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly categories: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Categories';
    };
    readonly category_translations: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'CategoryTranslations';
    };
    readonly ingredient_translations: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'IngredientTranslations';
    };
    readonly ingredients: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Ingredients';
    };
    readonly recipe_step_translations: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'RecipeStepTranslations';
    };
    readonly recipe_steps: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'RecipeSteps';
    };
    readonly recipe_translations: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'RecipeTranslations';
    };
    readonly recipes: { readonly namespace: 'public' & NamespaceId; readonly model: 'Recipes' };
    readonly unit_translations: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'UnitTranslations';
    };
    readonly units: { readonly namespace: 'public' & NamespaceId; readonly model: 'Units' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Categories: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int8@1' };
              };
              readonly slug: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly categoryTranslations: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'CategoryTranslations';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['categoryId'];
                };
              };
              readonly recipes: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Recipes';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['categoryId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'categories';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly slug: { readonly column: 'slug' };
              };
            };
          };
          readonly CategoryTranslations: {
            readonly fields: {
              readonly categoryId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int8@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int8@1' };
              };
              readonly languageCode: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 10 };
                };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly category: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Categories';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['categoryId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'category_translations';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly categoryId: { readonly column: 'category_id' };
                readonly id: { readonly column: 'id' };
                readonly languageCode: { readonly column: 'language_code' };
                readonly name: { readonly column: 'name' };
              };
            };
          };
          readonly Ingredients: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int8@1' };
              };
            };
            readonly relations: {
              readonly ingredientTranslations: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'IngredientTranslations';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['ingredientId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'ingredients';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly createdAt: { readonly column: 'created_at' };
                readonly id: { readonly column: 'id' };
              };
            };
          };
          readonly IngredientTranslations: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int8@1' };
              };
              readonly ingredientId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int8@1' };
              };
              readonly languageCode: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 10 };
                };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly ingredient: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Ingredients';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['ingredientId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'ingredient_translations';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly ingredientId: { readonly column: 'ingredient_id' };
                readonly languageCode: { readonly column: 'language_code' };
                readonly name: { readonly column: 'name' };
              };
            };
          };
          readonly Recipes: {
            readonly fields: {
              readonly authorId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly categoryId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int8@1' };
              };
              readonly cookingTime: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly createdAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int8@1' };
              };
              readonly imageUrl: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly servings: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly updatedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly category: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Categories';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['categoryId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly recipeSteps: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'RecipeSteps';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['recipeId'];
                };
              };
              readonly recipeTranslations: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'RecipeTranslations';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['recipeId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'recipes';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly authorId: { readonly column: 'author_id' };
                readonly categoryId: { readonly column: 'category_id' };
                readonly cookingTime: { readonly column: 'cooking_time' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly id: { readonly column: 'id' };
                readonly imageUrl: { readonly column: 'image_url' };
                readonly servings: { readonly column: 'servings' };
                readonly updatedAt: { readonly column: 'updated_at' };
              };
            };
          };
          readonly RecipeSteps: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int8@1' };
              };
              readonly imageUrl: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly recipeId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int8@1' };
              };
              readonly stepNumber: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly recipe: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Recipes';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['recipeId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly recipeStepTranslations: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'RecipeStepTranslations';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['stepId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'recipe_steps';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly imageUrl: { readonly column: 'image_url' };
                readonly recipeId: { readonly column: 'recipe_id' };
                readonly stepNumber: { readonly column: 'step_number' };
              };
            };
          };
          readonly RecipeStepTranslations: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int8@1' };
              };
              readonly instruction: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly languageCode: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 10 };
                };
              };
              readonly stepId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int8@1' };
              };
            };
            readonly relations: {
              readonly step: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'RecipeSteps';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['stepId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'recipe_step_translations';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly instruction: { readonly column: 'instruction' };
                readonly languageCode: { readonly column: 'language_code' };
                readonly stepId: { readonly column: 'step_id' };
              };
            };
          };
          readonly RecipeTranslations: {
            readonly fields: {
              readonly description: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int8@1' };
              };
              readonly languageCode: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 10 };
                };
              };
              readonly recipeId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int8@1' };
              };
              readonly title: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly recipe: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Recipes';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['recipeId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'recipe_translations';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly description: { readonly column: 'description' };
                readonly id: { readonly column: 'id' };
                readonly languageCode: { readonly column: 'language_code' };
                readonly recipeId: { readonly column: 'recipe_id' };
                readonly title: { readonly column: 'title' };
              };
            };
          };
          readonly Units: {
            readonly fields: {
              readonly code: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 50 };
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int8@1' };
              };
            };
            readonly relations: {
              readonly unitTranslations: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'UnitTranslations';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['unitId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'units';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly code: { readonly column: 'code' };
                readonly id: { readonly column: 'id' };
              };
            };
          };
          readonly UnitTranslations: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int8@1' };
              };
              readonly label: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 50 };
                };
              };
              readonly languageCode: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 10 };
                };
              };
              readonly unitId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int8@1' };
              };
            };
            readonly relations: {
              readonly unit: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Units';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['unitId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'unit_translations';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly label: { readonly column: 'label' };
                readonly languageCode: { readonly column: 'language_code' };
                readonly unitId: { readonly column: 'unit_id' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly insertOnConflictSkip: true;
      readonly insertOnConflictWithoutTarget: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
